[package]
name = "memnarch-rs"
version = "0.1.0"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
serde = "1"
serde_json ="1"
itertools = "0.8"
rand = "0.7"
simsearch = "0.1.4"
regex = "1"
lazy_static = "1"
unicase = "2"
reqwest = "0.11"
tempfile = "3"
songbird = "0.1"
futures = "0.3"
daemons = { git = "https://github.com/mendess/daemons" }
git-describe = { git = "https://github.com/mendess/git-describe", version = "0.2" }
serenity = { version = "0.10", features = ["collector"] }
anyhow = "1"
dashmap = "4"
log = "0.4"
simplelog = "0.10"
humantime = "2"
nom = { version = "6", features = ["regexp"] }
procinfo = "0.4"
toml = "0.5"

[dependencies.tokio]
version = "1"
features = ["rt", "rt-multi-thread", "io-util", "macros", "sync"]

[dev-dependencies]
paste = "*"
proptest = "0.9"

[profile.release]
codegen-units = 1
