[package]
name = "memnarch-rs"
version = "0.1.0"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4"
itertools = "0.8"
rand = "0.7"
simsearch = "0.1.4"
regex = "1"
lazy_static = "1"
unicase = "2"
tempfile = "3"
songbird = "0.3"
dashmap = { version = "5.0.0", features = ["serde"] }
log = "0.4"
simplelog = "0.10"
humantime = "2"
nom = { version = "6", features = ["regexp"] }
procinfo = "0.4"
toml = "0.5"
num-traits = "0.2.14"
bot-api = { path = "./bot-api" }
daemons = { git = "https://github.com/mendess/daemons" }
git-describe = { git = "https://github.com/mendess/git-describe", version = "0.2" }
mtg-spoilers = { git = "https://github.com/mendess/mtg-spoilers" }
serenity.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
reqwest.workspace = true
tokio.workspace = true
console-subscriber = "0.1.8"

[workspace.dependencies.tokio]
version = "1"
features = ["rt", "rt-multi-thread", "io-util", "macros", "sync", "tracing"]

[dev-dependencies]
paste = "*"
proptest = "0.9"

[workspace]
members = ["py-eval", "bot-api", "bot-api-types"]

[workspace.dependencies]
serenity = { version = "0.11", features = ["collector"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
reqwest = "0.11"
