[package]
name = "memnarch-rs"
version = "0.1.0"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2021"

[dependencies]
anyhow.workspace = true
bot-api = { path = "./bot-api" }
chrono = "0.4"
console-subscriber = "0.1.8"
daemons = { git = "https://github.com/mendess/discord-bot-utils", features = ["cron"] }
futures.workspace = true
git-describe = { git = "https://github.com/mendess/git-describe", version = "0.2" }
itertools = "0.10"
json-db = { git = "https://github.com/mendess/discord-bot-utils" }
log = "0.4"
mtg-spoilers = { git = "https://github.com/mendess/mtg-spoilers" }
nom = "7"
nom-regex = "0.2"
num-traits = "0.2.14"
pubsub = { git = "https://github.com/mendess/discord-bot-utils", features = ["serenity_cache"] }
rand = "0.8"
regex = "1"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serenity.workspace = true
simplelog = "0.12"
simsearch = "0.1.4"
songbird = "0.3"
tempfile = "3"
toml = "0.7"
unicase = "2"

[dependencies.tokio]
workspace = true
features = ["rt", "rt-multi-thread", "io-util", "macros", "sync", "tracing"]

[dev-dependencies]
paste = "1"
proptest = "1"

[workspace]
members = ["py-eval", "bot-api", "bot-api-types"]

[workspace.dependencies]
anyhow = "1"
futures = "0.3"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serenity = { version = "0.11", features = ["collector"] }

[workspace.dependencies.tokio]
version = "1"

[workspace.dependencies.actix-web]
version = "4.1.0"
default-features = false
